language: r
r:
  - release
  - devel

cache: packages
sudo: false

warnings_are_errors: true

r_github_packages:
  - r-lib/covr

addons:
  apt:
    packages:
      - devscripts
      - libv8-dev
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -fext-numeric-literals" >> ~/.R/Makevars

after_success:
  - Rscript -e 'library(covr);codecov()'
