language: r
r:
  - release
  - devel

cache: packages
sudo: false

warnings_are_errors: true

r_github_packages:
  - r-lib/covr

addons:
  apt:
    packages:
      - devscripts
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -DBOOST_MATH_DISABLE_FLOAT128 -O3" >> ~/.R/Makevars

after_success:
  - Rscript -e 'library(covr);codecov()'
